export const TEACHER_ROUTE = '/teacher'
export const STUDENT_ROUTE = '/student'
export const SETTINGS_ROUTE = '/settings'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const TOPIC_ROUTE = '/topic'
export const TEST_ROUTE = '/test'