BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `product` (
	`idProduct`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`title`		TEXT NOT NULL UNIQUE,
	`optprice`	INTEGER NOT NULL,
	`rozprice`	TEXT NOT NULL,
	`description`	VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS `deal` (
	`idDeal`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`dealdate`	DATE NOT NULL,
	`idProduct`	INTEGER NOT NULL UNIQUE,
	`kolvo`		INTEGER NOT NULL,
	`idCustomer`	INTEGER NOT NULL UNIQUE,
	`isOpt`		BOOLEAN NOT NULL,
	FOREIGN KEY(`idProduct`) REFERENCES `product`(`idProduct`) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(`idCustomer`) REFERENCES `customer`(`idCustomer`) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS `customer` (
	`idCustomer`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`phone`		TEXT NOT NULL UNIQUE,
	`name`		TEXT NOT NULL UNIQUE,
	`address`	TEXT NOT NULL UNIQUE
);
COMMIT;
