version: '3.4'

services:
  lab4:
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  db:
    ports: 
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: asp_net_lab4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1!
    volumes:
      - lab4-db-data:/var/lib/postgresql/data
    