// <auto-generated />
using Lab3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Lab3.Migrations
{
    [DbContext(typeof(GroupContext))]
    partial class GroupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Lab3.Models.GroupModel", b =>
                {
                    b.Property<int>("idgroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("idgroup");

                    b.ToTable("group");

                    b.HasData(
                        new
                        {
                            idgroup = 1,
                            name = "ДИПРБ 1"
                        },
                        new
                        {
                            idgroup = 2,
                            name = "ДИПРБ 2"
                        });
                });

            modelBuilder.Entity("Lab3.Models.StudentModel", b =>
                {
                    b.Property<int>("idstudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FIO")
                        .HasColumnType("text");

                    b.Property<bool>("headman_sign")
                        .HasColumnType("boolean");

                    b.Property<int>("idgroup")
                        .HasColumnType("integer");

                    b.HasKey("idstudent");

                    b.HasIndex("idgroup");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            idstudent = 1824,
                            FIO = "студент1",
                            headman_sign = true,
                            idgroup = 1
                        },
                        new
                        {
                            idstudent = 7178,
                            FIO = "студент2",
                            headman_sign = false,
                            idgroup = 1
                        },
                        new
                        {
                            idstudent = 78783,
                            FIO = "студент3",
                            headman_sign = true,
                            idgroup = 2
                        },
                        new
                        {
                            idstudent = 78785,
                            FIO = "студент4",
                            headman_sign = false,
                            idgroup = 2
                        });
                });

            modelBuilder.Entity("Lab3.Models.StudentModel", b =>
                {
                    b.HasOne("Lab3.Models.GroupModel", null)
                        .WithMany()
                        .HasForeignKey("idgroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
