version: '3.4'

services:
  lab3:
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  db:
    environment:
      POSTGRES_DB: asp_net_lab3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1!
    